#!/usr/bin/env python3
"""Reproduce and verify three complete e=2 zero-at-origin corner exclusions.

Default: verify the stored rational polynomial duals using the standard
library only. --regenerate: use SymPy and M2 to rebuild the ancestor lifts,
one-variable module calculations, and JSON certificate from the audited
tensor. The theorem has the scope stated in the companion session note.
"""
from fractions import Fraction as Q
from pathlib import Path
import hashlib
import json
import subprocess
import sys

HERE = Path(__file__).resolve().parent
CERT = HERE / 'session-localcoh-corners-certificate.json'
COORDINATES = ['localcoh-incidence-tensor.txt', 'localcoh-incidence-bases.txt',
               'localcoh-symbol-top.json', 'localcoh-symbol-numerators.txt']


def regenerate():
    import sympy as s
    top = json.loads((HERE / 'localcoh-symbol-top.json').read_text())
    M = s.Matrix(top['matrix'])
    pivots = M.rref()[1]
    independent = M[:, pivots]
    independent_rows = independent.T.rref()[1]
    inverse = independent[list(independent_rows), :].inv()
    kernel = M.nullspace()[0]
    tensor = s.zeros(74, 542)
    for line in (HERE / COORDINATES[0]).read_text().splitlines()[1:]:
        row, col, value = line.split()
        tensor[int(row), int(col)] = s.Rational(value)
    t, parameter = s.symbols('t lambda')
    directions = [('corner18', 1+t, -6*t+18*t*t),
                  ('corner2', 1+t-t*t, 2*t*t),
                  ('corner10', 1+t-t*t, 10*t*t)]
    cases = []
    for label, p, r in directions:
        pure = s.Matrix([s.expand(t*p**i*r**(3-i)).coeff(t, j)
                         for i in range(4) for j in range(8)])
        assert s.Matrix(top['annihilator'])*pure == s.zeros(3, 1)
        seed = s.zeros(30, 1)
        for index, value in zip(pivots, inverse*pure[list(independent_rows), :]):
            seed[index] = value
        assert M*seed == pure and M*kernel == s.zeros(32, 1)
        ancestor = seed + parameter*kernel
        matrix = s.Matrix(74, 18, lambda row, col: s.expand(sum(
            tensor[row, 18*i+col]*ancestor[i] for i in range(30))))
        def m2(value):
            return str(value).replace('**', '^')
        script = [
            '-- Generated by session-localcoh-corners.py --regenerate.',
            'R=QQ[lambda];',
            'L=matrix{' + ','.join('{' + ','.join(m2(v) for v in matrix.row(row))
                                      + '}' for row in range(74)) + '};',
            'K=gens kernel transpose L;',
            'U=matrix{' + ','.join('{' + str(int(row == 72)) + '}'
                                  for row in range(74)) + '};',
            'E=transpose U*K; J=ideal E;',
            'assert(J==ideal(1_R));',
            'c=matrix{{1_R}} // E; n=K*c;',
            'assert(transpose n*L==0); assert(transpose n*U==matrix{{1_R}});',
            'ff=openOut "research/computations/session-localcoh-' + label + '-dual.txt";',
            'for row from 0 to 73 do ff << row << " " << toString n_(row,0) << endl;',
            'close ff;',
            'print "PASS: exact polynomial dual excludes u for every lambda";',
            'exit 0;'
        ]
        script_path = HERE / ('session-localcoh-' + label + '.m2')
        script_path.write_text('\n'.join(script) + '\n')
        subprocess.run(['M2', '--script', str(script_path)], cwd=HERE.parent.parent,
                       check=True)
        dual = []
        for row, line in enumerate((HERE / ('session-localcoh-' + label + '-dual.txt'))
                                   .read_text().splitlines()):
            index, value = line.split(maxsplit=1)
            assert int(index) == row
            polynomial = s.Poly(s.sympify(value.replace('^', '**').replace('lambda', 'lam'),
                                         locals={'lam': parameter}), parameter)
            dual.append([[power[0], str(coefficient)]
                         for power, coefficient in polynomial.terms() if coefficient])
        cases.append({'label': label,
                      'p': [str(s.expand(p).coeff(t, i)) for i in range(3)],
                      'r': [str(s.expand(r).coeff(t, i)) for i in range(3)],
                      'seed': list(map(str, seed)), 'kernel': list(map(str, kernel)),
                      'dual': dual})
    CERT.write_text(json.dumps({
        'coordinate_sha256': {name: hashlib.sha256((HERE/name).read_bytes()).hexdigest()
                              for name in COORDINATES},
        'scope': 'primitive e=2, h=t, r(0)=0, p(0)=1; three torus-normalized cases',
        'cases': cases}, indent=2) + '\n')


def add(first, second):
    answer = dict(first)
    for power, coefficient in second.items():
        answer[power] = answer.get(power, Q(0)) + coefficient
        if not answer[power]:
            del answer[power]
    return answer


def scale(polynomial, value):
    return {power: coefficient*value for power, coefficient in polynomial.items()
            if coefficient*value}


def multiply(first, second):
    answer = {}
    for i, a in first.items():
        for j, b in second.items():
            answer = add(answer, {i+j: a*b})
    return answer


def power(polynomial, exponent):
    answer = {0: Q(1)}
    for _ in range(exponent):
        answer = multiply(answer, polynomial)
    return answer


def verify():
    data = json.loads(CERT.read_text())
    for name, expected in data['coordinate_sha256'].items():
        assert hashlib.sha256((HERE/name).read_bytes()).hexdigest() == expected, name
    lines = (HERE / COORDINATES[0]).read_text().splitlines()
    assert lines[0] == '30 18 74 542'
    tensor = [[Q(0)]*542 for _ in range(74)]
    for line in lines[1:]:
        row, col, value = line.split()
        tensor[int(row)][int(col)] = Q(value)
    assert [row[540] for row in tensor] == [Q(i == 72) for i in range(74)]
    assert [row[541] for row in tensor] == [Q(i == 73) for i in range(74)]
    bases = (HERE / COORDINATES[1]).read_text().splitlines()
    assert bases[1:31] == (HERE / COORDINATES[3]).read_text().splitlines()
    M = [[Q(value) for value in row] for row in
         json.loads((HERE / COORDINATES[2]).read_text())['matrix']]
    for case in data['cases']:
        seed, kernel = list(map(Q, case['seed'])), list(map(Q, case['kernel']))
        p = {i: Q(value) for i, value in enumerate(case['p']) if Q(value)}
        r = {i: Q(value) for i, value in enumerate(case['r']) if Q(value)}
        top = []
        for i in range(4):
            polynomial = multiply({1: Q(1)}, multiply(power(p, i), power(r, 3-i)))
            top.extend(polynomial.get(j, Q(0)) for j in range(8))
        assert [sum(a*b for a, b in zip(row, seed)) for row in M] == top
        assert all(sum(a*b for a, b in zip(row, kernel)) == 0 for row in M)
        dual = [{int(exponent): Q(value) for exponent, value in terms}
                for terms in case['dual']]
        assert dual[72] == {0: Q(1)}
        for col in range(18):
            result = {}
            for row in range(74):
                entry = {0: sum(tensor[row][18*i+col]*seed[i] for i in range(30)),
                         1: sum(tensor[row][18*i+col]*kernel[i] for i in range(30))}
                result = add(result, multiply(dual[row], entry))
            assert not result, (case['label'], col, result)
        print('PASS:', case['label'], 'pure-top lift and all 18 polynomial-dual identities; n^T u=1.')
    print('PROVED: all three normalized primitive corner directions exclude u for every lower coefficient.')


if __name__ == '__main__':
    if '--regenerate' in sys.argv:
        regenerate()
    verify()
