#!/usr/bin/env python3
"""Lift the full pure-cubic parity family into the exact 30-dimensional E4.

Direction p=a0+a2*t^2, r=b1*t, coefficient h=1. Export the ten homogeneous
parameter-coefficient vectors to M2 for a uniform multiplication exclusion.
This generated file is tied to localcoh-symbol-export.m2's exact Ext basis.
"""
from pathlib import Path
import json
import sympy as s
ROOT=Path(__file__).resolve().parent
D=json.loads((ROOT/'localcoh-symbol-top.json').read_text())
M=s.Matrix([[s.sympify(v) for v in row] for row in D['matrix']])
L=s.Matrix(D['annihilator'])
t,a0,a2,b1=s.symbols('t a0 a2 b1')
p=a0+a2*t*t;r=b1*t
v=s.Matrix([s.expand(p**i*r**(3-i)).coeff(t,j) for i in range(4) for j in range(8)])
assert L*v==s.zeros(3,1)
z,params=M.gauss_jordan_solve(v)
z=z.subs({param:0 for param in params})
assert M*z==v
polys=[s.Poly(s.expand(zz),a0,a2,b1) for zz in z]
monomials=sorted(set(m for poly in polys for m in poly.monoms()))
assert len(monomials)==10 and all(sum(m)==3 for m in monomials)
coeffs=[[poly.coeff_monomial(m) for poly in polys] for m in monomials]
(ROOT/'localcoh-symbol-parity-coordinates.m2').write_text(
    '-- Generated by localcoh-symbol-parity.py.\n'
    '-- Parameter monomial order: '+str(monomials)+'\n'
    +'parityCoeffs={'+','.join('{'+','.join(str(a) for a in row)+'}' for row in coeffs)+'};\n')
(ROOT/'localcoh-symbol-parity.json').write_text(json.dumps({
    'direction':['a0+a2*t^2','b1*t'],'top_coefficient':'1',
    'parameter_monomials':monomials,
    'basis_coefficient_vectors':[[str(v) for v in row] for row in coeffs],
    'warning':'Top lifting by itself is not an ancestor; run the M2 multiplication certificate.'
},indent=2)+'\n')
print('PASS: full degree-two parity family lifts; exported ten exact parameter-coefficient seeds')
