#!/usr/bin/env python3
"""Export the remaining h=t endpoint chart as a small quotient-module problem.

Normalization uses only common direction scaling and the actual torus of
C0: p(0)=r(0)=1. Three cubic top-image equations, five variables including
the lower correction. The exported M2 calculation is exploratory until an
independent exact certificate is saved. No bilinear multiplier variables.
"""
from pathlib import Path
import json
import sympy as s

HERE = Path(__file__).resolve().parent
top = json.loads((HERE/'localcoh-symbol-top.json').read_text())
M = s.Matrix(top['matrix'])
pivots = M.rref()[1]
independent = M[:, pivots]
independent_rows = independent.T.rref()[1]
inverse = independent[list(independent_rows), :].inv()
kernel = M.nullspace()[0]
tensor = s.zeros(74, 542)
for line in (HERE/'localcoh-incidence-tensor.txt').read_text().splitlines()[1:]:
    row, col, value = line.split()
    tensor[int(row), int(col)] = s.Rational(value)
a1, a2, b1, b2, parameter, t = s.symbols('a1 a2 b1 b2 lambda t')
p = 1+a1*t+a2*t*t
r = 1+b1*t+b2*t*t
pure = s.Matrix([s.expand(t*p**i*r**(3-i)).coeff(t, j)
                 for i in range(4) for j in range(8)])
constraints = s.Matrix(top['annihilator'])*pure
seed = s.zeros(30, 1)
for index, value in zip(pivots, inverse*pure[list(independent_rows), :]):
    seed[index] = value
ancestor = seed+parameter*kernel
matrix = s.Matrix(74, 18, lambda row, col: s.expand(sum(
    tensor[row, 18*i+col]*ancestor[i] for i in range(30))))
delta = s.resultant(p, r, t)
def m2(value):
    return str(s.expand(value)).replace('**', '^')
script = [
    '-- Generated by session-localcoh-origin-generic.py; exploratory.',
    'P=QQ[a1,a2,b1,b2,lambda];',
    'Jtop=ideal(' + ','.join(m2(value) for value in constraints) + ');',
    'print("top ideal ready");',
    'R=P/Jtop;',
    'L=matrix{' + ','.join('{' + ','.join(m2(value) for value in matrix.row(row)) + '}'
                          for row in range(74)) + '};',
    'delta=' + m2(delta) + ';',
    'U=matrix{' + ','.join('{' + str(int(row == 72)) + '}' for row in range(74)) + '};',
    'print("matrix ready: 74x18 over five-variable quotient by three cubics");',
    'K=gens kernel transpose L;',
    'print("dual module computed");',
    'E=transpose U*K; J=ideal E;',
    'ff=openOut "research/computations/session-localcoh-origin-generic-dual-ideal.txt";',
    'ff << "dual evaluations:" << endl << gens gb J << endl;',
    'close ff;',
    'print("dual evaluation ideal saved");',
    'Jprimitive=saturate(J,ideal(delta));',
    'ff=openOut "research/computations/session-localcoh-origin-generic-saturated.txt";',
    'ff << gens gb Jprimitive << endl; close ff;',
    'print("primitive saturation saved");',
    'if Jprimitive==ideal(1_R) then (',
    '  exponent=0; while ((delta^exponent)%J)!=0 do exponent=exponent+1;',
    '  c=matrix{{delta^exponent}} // E; n=K*c;',
    '  assert(transpose n*L==0); assert(transpose n*U==matrix{{delta^exponent}});',
    '  ff=openOut "research/computations/session-localcoh-origin-generic-dual.txt";',
    '  ff << "resultant exponent " << exponent << endl;',
    '  for row from 0 to 73 do ff << row << " " << toString lift(n_(row,0),P) << endl;',
    '  close ff; print("EXCLUSION candidate: exact dual modulo top equations")',
    ');',
    'exit 0;'
]
destination = HERE/'session-localcoh-origin-generic.m2'
destination.write_text('\n'.join(script)+'\n')
(HERE/'session-localcoh-origin-generic-chart.json').write_text(json.dumps({
    'p': str(p), 'r': str(r), 'h': 't',
    'constraints': list(map(str, constraints)), 'resultant': str(delta),
    'scope': 'primitive e=2 with top zero at t=0 and r(0) nonzero; torus p0=r0=1',
    'status': 'EXACT CHART; MODULE CALCULATION EXPLORATORY'
}, indent=2)+'\n')
print(destination)
